name: myphp
on:
  push: # push 时触发, 主要是为了测试配置有没有问题
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '*/5 * * * *'

jobs:
  crawler:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: PHP Composer
        # You may pin to the exact commit or the version.
        # uses: baschny/php-composer-action@93b5aef92179c5ebba8824db8d34748301c6a70e
        uses: baschny/php-composer-action@v1

      - name: Update
        run: |
          php ./my.php
        shell: bash

      - name: commit
        run: |
          git config --global user.name 40740
          git pull
          git add .
          git commit -m "Crawler By Github Actions"  -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GI_TOKEN }}
