name: myphp
on:
  push: # push 时触发, 主要是为了测试配置有没有问题
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '*/5 * * * *'

jobs:
  crawler:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4' 

      - name: Update
        run: |
          php ./my.php
        shell: bash

      - name: commit
        run: |
          git config --global user.name 40740
          git pull
          git add .
          git commit -m "Crawler By Github Actions"  -a
#       - name: Push changes
#         uses: ad-m/github-push-action@master
#         with:
#           github_token: ${{ secrets.GI_TOKEN }}
